#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

static void print_header(FILE* out, char *pfx, int dostatic) {
	char *visib = dostatic ? "static " : "";
	fprintf(out,
		"#include <string.h>\n"
		"%svoid %sreset (void) {}\n"
		"%svoid %soutput_statistics (void) {}\n"
		"%sint  %sfind_keyword (const char *keyword, int length) {\n",
		visib, pfx,
		visib, pfx,
		visib, pfx);
}

static int usage() {
	fprintf(stderr, "%s",
		"minishilka [OPTIONS] descriptionfile.shilka\n\n"
		"minishilka is a small replacement for shilka which generates code\n"
		"for fast keyword search. minishilka only supports a single usecase\n"
		"of shilka, namely the one i use.\n"
		"it's meant to be used if compiling the real shilka program would be too much\n"
		"of a hassle. minishilka produces somewhat slower, but still quite fast code.\n"
		"output is written to XXX.c, where XXX is the descriptionfile sans extension.\n"
		"\n"
		"a supported input file starts with a line containing '%%', followed\n"
		"by one or more lines containing a plain keyword followed by whitespace\n"
		"and an action statement written in C, e.g.\n\n"
		"while              {return KEYWORD_TOKEN_WHILE;}\n"
		"the last line in the file may be %other {action-if-no-keyword-matches}\n"
		"if the %other statement is not provided, -1 is returned if none of the\n"
		"keywords match.\n"
		"\nOPTIONS\n"
		"-pprefix - use prefix instead of KR_ for the generated function names.\n"
		"-case - use strcasecmp for keyword comparison instead of memcmp\n"
		"-no-definitions - this shilka mode is default for mini-shilka and ignored\n"
		"-inline - ignored\n"
		"\nNOTES\n"
		"the code generated by minishilka is especially tiny when the value returned\n"
		"in the C statement is identical to the linenumber (minus %%), for example\n"
		"if the first line returns 0, the second 1, and so on.\n"
		"if encountering such code at higher optimization levels, GCC recognizes that\n"
		"the value of the loop counter is identical to what gets assigned in the\n"
		"switch statement and optimizes the latter away completely.\n"
	);
	return 1;
}

struct item {
	char *kw;
	char *action;
	size_t length;
	struct item* next;
};

/* to piss off newchurch zealots :-) */
#define master main

int master(int argc, char** argv) {
	int i = 0, o_case = 0;
	char* pfx = "KR_";
	while(++i < argc) {
		if(argv[i][0] != '-') break;
		switch(argv[i][1]) {
		case 'p': pfx=argv[i]+2; break;
		case 'i':
			if(!strcmp(argv[i]+1, "inline")) ; /* o_inl = 1; */
			else return usage();
			break;
		case 's':
			if(!strcmp(argv[i]+1, "strip")) ; /* o_strip = 1; */
			else return usage();
			break;
		case 'c':
			if(!strcmp(argv[i]+1, "case")) o_case = 1;
			else return usage();
			break;
		case 'n':
			if(!strcmp(argv[i]+1, "no-definitions")) ; /* default */
			else return usage();
			break;
		default:
			return usage();
		}
	}
	if(argc == i) return usage();

	char buf[1024], *other = 0, *p, *q;
	FILE *in = fopen(argv[i], "r"), *out;
	if(!in) {
		perror("fopen");
		return 1;
	}
	snprintf(buf, sizeof buf, "%s", argv[i]);
	if((p = strrchr(buf, '.'))) {
		*(++p) = 'c';
		*(++p) = 0;
	} else strcat(buf, ".c");
	out = fopen(buf, "w");
	if(!out) {
		perror("fopen");
		return 1;
	}

	int seen = 0;
	size_t maxlen = 0;
	struct item *list = 0, *last = 0;
	while(fgets(buf, sizeof buf, in)) {
		p = strrchr(buf, '\n');
		if(p) *p = 0;

		if(buf[0] == 0) continue;
		if(!seen && strcmp(buf, "%%")) {
			fprintf(stderr, "mini-shilka file must begin with %%\n");
			return 1;
		}
		if(!seen) {
			seen = 1;
			print_header(out, pfx, 1);
			continue;
		}
		p = buf;
		while(!isspace(*p))++p;
		*p = 0;

		q = p+1;
		while(isspace(*q))++q;
		if(!strcmp(buf, "%other")) {
			other = q;
			continue;
		}
		struct item *it = calloc(1, sizeof(*it));
		it->kw = strdup(buf);
		it->action = strdup(q);
		it->length = strlen(buf);
		it->next = 0;
		if(!list) {
			list=it;
			last=it;
		} else {
			last->next = it;
			last = it;
		}
		if(it->length > maxlen) maxlen = it->length;
	}

	fprintf(out, "\tstatic const char keywords[][%zu] = {\n", maxlen+1+o_case);
	struct item *it;
	for(it = list; it; it = it->next) {
		fprintf(out, "\t\t\"\\%03o%s\",\n", (unsigned)it->length, it->kw);
	}

	fprintf(out,
		"\t};\n"
		"\tint i;\n"
		"\tfor(i=0; i<sizeof(keywords)/sizeof(keywords[0]); ++i) {\n"
		"\t\tif(length == (int)keywords[i][0] && !%s(keywords[i]+1, keyword%s))\n"
		"\t\t\tbreak;\n"
		"\t}\n"
		"\tswitch(i) {\n",
		o_case ? "strcasecmp" : "memcmp", o_case ? "" : ", length"
	);

	for(i = 0, it = list; it; ++i, it = it->next) {
		fprintf(out, "\tcase %d: %s ; break;\n", i, it->action);
	}

	fprintf(out, "\tdefault: %s\n", other ? other : "return -1;");
	fprintf(out, "%s", "\t}\n\treturn -1;\n}\n");

	fclose(in);
	fclose(out);
	return 0;
}
